### ISSUE TITLE
[BUG] Issue title

### ISSUE THREAD

**Issue by masterlittle** [hoptical/nodegraph-api-plugin#17]
**Describe the bug**
On clicking the nodes or edges cannot see the context menu in Graph View.

**To Reproduce**
1. Create a Nodegraph API plugin.
2. Click on nodes or edges.
3. No additional popup can be seen.

**Expected behavior**
A context menu should open.

**Data being sent**
{
        "edges": [
            {
                "id": "1",
                "mainStat": "53/s",
                "secondaryStat": "hello",
                "displayName": "s,sd,d,sdcdsfc,sdfsc",
                "source": "1",
                "target": "2"
            }
        ],
        "nodes": [
            {
                "arc__passed": 1,
                "displayName": "load",
                "id": "1",
                "subTitle": "instance:#2",
                "title": "T"
            },
            {
                "arc__passed": 1,
                "displayName": "transform",
                "id": "2",
                "subTitle": "instance:#3",
                "title": "P"
            }
        ]
    }

**Desktop Information:**
 - Plugin Version >> latest
 - Grafana Version >> 9.0.1

**Comment by hoptical** [comment]
Thanks for reporting. Actually, this should be related to the [node graph panel](https://grafana.com/docs/grafana/latest/visualizations/node-graph/) itself and not this data source. This data source is just a middleware to provide data via API.
I've reported this [issue ](https://github.com/grafana/grafana/issues/51410)on the Grafana repository. Hope to proceed well.

**Comment by alex-necula** [comment]
Hello,
I'm experiencing the same problem even on v9.1.0. It seems that they closed the Grafana issue on their part

**Comment by hoptical** [comment]
Hi @alex-necula,
Thanks for reaching out. As you said, and unfortunately, Grafana has closed the [issue](https://github.com/grafana/grafana/issues/53373). I'm pretty sure that this is on the Grafana side but will check it again on the plugin side for more certainty. I'll get back to you in a few days.

**Comment by perotta** [comment]
I'm also experiencing the same issue on grafana 9.1.6

Tried Chrome and Browser on Ubuntu 20.04 with no luck

I agree it looks like a problem on the Node Graph plugin, but it almost sound like a data format problem?

It's hard to find 'oficial' data samples to double check the data format

**Comment by hoptical** [comment]
@perotta 
I'm sorry for the very late reply. I'd problems with the internet connection in my country. 

What do you mean by data format? Would you explain more, please?

**Comment by perotta** [comment]
Hi @hoptical I'm glad you are back :)

I got to solve this issue after a lot of digging.

First part: Grafana was not showing Context Menu if there were no links. The Grid Layout has a link to go back to Node Graph Layout, so that's why the Context Menu would show. Altough it was not really a "bug" on their side, they changed it to always show Context Menu even if there's no links.

https://github.com/grafana/grafana/issues/51410
https://github.com/grafana/grafana/issues/55838

It also took me some time to understand what "links" were. Basically anything that shows below the basic information on the Context Menu are your "links". Their declaration can be pretty complex as they can link to inner parts Grafana (Like showing Traces in their Demo example). But they can also simply link to an external URL, which was what I wanted.

![image_2023-02-10_11-01-10](https://user-images.githubusercontent.com/45238586/218164484-4f8ce2a0-052f-4752-ada1-fe93fd654bd3.png)

Second part: After determining that what I needed was a way to get this "links" array inside the datasource, I edited nodegraph-api code to accept under link whatever you want to put on links (litteraly a 3 lines soultion) and I'm using my own unsigned version of nodegraph-api. Theres a screenshot of what the structure looks like in my PR.

https://github.com/hoptical/nodegraph-api-plugin/pull/23

It works very well, but it would be nice to drop my unsigned plugin and just use the official one instead.

I don't want to be picky, but I think you should adopt PR 23 instead of PR 21, their implementation seems fragile as they basically are duplicating Grafana's Node Graph link structure.

This is what my fields declaration looks like (my code is in PHP but I will simply json_encode this return to server it to nodegraph-api)
![image_2023-02-10_11-12-18](https://user-images.githubusercontent.com/45238586/218166064-a2555293-fa6d-4dd0-b21d-7316933b1c61.png)
